{
  "openapi": "3.0.0",
  "info": {
    "title": "webhook.payload.v1",
    "version": "1.0.1"
  },
  "servers": [
    {
      "url": "http://selfdefined.url.for.recieving.webhooks"
    }
  ],
  "paths": {
    "/customer.defined.root.event.webhook.path": {
      "parameters": [],
      "post": {
        "summary": "OPCP Root Payload",
        "operationId": "post-users-userId",
        "responses": {
          "200": {
            "description": "Webhook received successfully"
          },
          "400": {
            "description": "Invalid request"
          }
        },
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "header",
            "name": "content-type",
            "description": "application/json",
            "required": true
          },
          {
            "schema": {
              "type": "string",
              "example": "7808b566f4057216e64c6298bfd5a184d4d715ffec6599311e5266f48865"
            },
            "in": "header",
            "name": "payload-signature",
            "description": "Signatures using a hash-based message authentication code HMAC with SHA-256.",
            "required": true
          },
          {
            "schema": {
              "type": "string",
              "example": "sha256=7808b566f4057216e64c6298bfd5a184d4d715ffec6599311e5266f48865XXXX"
            },
            "in": "header",
            "name": "X-Hubject-Signature",
            "description": "Signatures using a hash-based message authentication code HMAC with SHA-256."
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "timestamp": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-02-03T00:00:00Z",
                    "description": "Timestamp when the event was created"
                  },
                  "eventId": {
                    "type": "string",
                    "description": "UUID of the event",
                    "format": "uuid",
                    "pattern": "^[0-9a-fA-F]{8}\\-([0-9a-fA-F]{4}\\-){3}[0-9a-fA-F]{12}$"
                  },
                  "eventType": {
                    "description": "root.cert.added\nroot.cert.expired\nroot.cert.revoked",
                    "enum": [
                      "root.cert.added",
                      "root.cert.expired",
                      "root.cert.revoked"
                    ]
                  },
                  "xsdMsgDefNamespace": {
                    "description": "Which ISO Version\n",
                    "example": "urn:iso:15118:2:2013:MsgDef",
                    "enum": [
                      "urn:iso:15118:2:2013:MsgDef",
                      "urn:iso:15118:20:2022:MsgDef"
                    ]
                  },
                  "payload": {
                    "type": "object",
                    "required": [
                      "rootCertificateId",
                      "distinguishedName",
                      "commonName",
                      "rootType"
                    ],
                    "properties": {
                      "rootCertificateId": {
                        "type": "string",
                        "format": "uuid",
                        "pattern": "^[0-9a-fA-F]{8}\\-([0-9a-fA-F]{4}\\-){3}[0-9a-fA-F]{12}$",
                        "example": "b1b86334-7c74-4ccc-b78d-d4f773d3b559",
                        "description": "UUID of the root "
                      },
                      "distinguishedName": {
                        "type": "string",
                        "pattern": "^(CN=[a-zA-Z0-9\\s\\-\\.]+,\\s)?(DC=[a-zA-Z0-9\\s\\-\\.]+,\\s)?(O=[a-zA-Z0-9\\s\\-\\.]+,\\s)?(OU=[a-zA-Z0-9\\s\\-\\.]+,\\s)?(C=[A-Z]{2})?$",
                        "example": "CN=V2G Root CA G2, DC=V2G, O=Hubject GmbH, C=DE",
                        "description": "Distingushed Name of the root for this event"
                      },
                      "commonName": {
                        "type": "string",
                        "example": "V2G Root CA G2",
                        "description": "Common Name of the Root of this event"
                      },
                      "rootType": {
                        "enum": [
                          "MO",
                          "OEM",
                          "V2G"
                        ],
                        "description": "Root type which is meant"
                      },
                      "rootSerialNumber": {
                        "type": "string",
                        "description": "serial number in hex format of the certificate",
                        "example": "bbbbbc1ac45ad2dfe5b1d873c35c84",
                        "pattern": "^[0-9a-fA-F]+$"
                      },
                      "signatureAlgorithm": {
                        "type": "string",
                        "enum": ["secp256r1", "secp521r1"],
                        "description": "Signature algorithm used"
                      },
                      "fingerprintSHA256": {
                        "type": "string",
                        "description": "SHA256 fingerprint of the certificate"
                      }
                    }
                  }
                },
                "required": [
                  "timestamp",
                  "eventId",
                  "eventType",
                  "payload"
                ]
              },
              "examples": {
                "ISO 15118-2 Example": {
                  "value": {
                    "timestamp": "2026-02-03T00:00:00Z",
                    "eventId": "b1b86334-7c74-4ccc-b78d-d4f773d3b559",
                    "eventType": "root.cert.added",
                    "xsdMsgDefNamespace": "urn:iso:15118:2:2013:MsgDef",
                    "payload": {
                      "rootCertificateId": "b1b86334-7c74-4ccc-b78d-d4f773d3b559",
                      "distinguishedName": "CN=V2G Root CA G2, DC=V2G, O=Hubject GmbH, C=DE",
                      "commonName": "V2G Root CA G2",
                      "rootType": "V2G",
                      "rootSerialNumber": "bbbbbc1ac45ad2dfe5b1d873c35c84",
                      "signatureAlgorithm": "secp256r1",
                      "fingerprintSHA256": "a76ae4c5d00e06a967554511865bfa89e79590e8a61b5a71f9ce22e039d6c370"
                    }
                  }
                },
                "ISO 15118-20 Example": {
                  "value": {
                    "timestamp": "2026-02-03T00:00:00Z",
                    "eventId": "c2c97445-8d85-5ddd-c89e-e5f884e4c660",
                    "eventType": "root.cert.added",
                    "xsdMsgDefNamespace": "urn:iso:15118:20:2022:MsgDef",
                    "payload": {
                      "rootCertificateId": "b1b86334-7c74-4ccc-b78d-d4f773d3b559",
                      "distinguishedName": "CN=V2G Root CA G2, DC=V2G, O=Hubject GmbH, C=DE",
                      "commonName": "V2G Root CA G2",
                      "rootType": "V2G",
                      "rootSerialNumber": "bbbbbc1ac45ad2dfe5b1d873c35c84",
                      "signatureAlgorithm": "secp521r1",
                      "fingerprintSHA256": "a76ae4c5d00e06a967554511865bfa89e79590e8a61b5a71f9ce22e039d6c370"
                    }
                  }
                }
              }
            }
          },
          "description": ""
        },
        "description": "This body will be used if events regarding a RCP change are fired.\n* root.cert.added\n* root.cert.expired\n* root.cert.revoked\n"
      }
    },
    "/customer.defined.pcid.emaid.event.webhook.path": {
      "parameters": [],
      "post": {
        "summary": "OPCP PCID EMAID Payload",
        "operationId": "post-root-users-userId",
        "responses": {
          "200": {
            "description": "Webhook received successfully"
          },
          "400": {
            "description": "Invalid request"
          }
        },
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "header",
            "name": "content-type",
            "description": "application/json",
            "required": true
          },
          {
            "schema": {
              "type": "string",
              "example": "7808b566f4057216e64c6298bfd5a184d4d715ffec6599311e5266f48865"
            },
            "in": "header",
            "name": "payload-signature",
            "description": "Signatures using a hash-based message authentication code HMAC with SHA-256.",
            "required": true
          },
          {
            "schema": {
              "type": "string",
              "example": "sha256=7808b566f4057216e64c6298bfd5a184d4d715ffec6599311e5266f48865XXXX"
            },
            "in": "header",
            "name": "X-Hubject-Signature",
            "description": "Signatures using a hash-based message authentication code HMAC with SHA-256."
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "timestamp",
                  "eventId",
                  "eventType",
                  "xsdMsgDefNamespace",
                  "payload"
                ],
                "properties": {
                  "timestamp": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-02-03T00:00:00Z",
                    "description": "Timestamp when the event was created"
                  },
                  "eventId": {
                    "type": "string",
                    "description": "UUID of the event",
                    "format": "uuid",
                    "pattern": "^[0-9a-fA-F]{8}\\-([0-9a-fA-F]{4}\\-){3}[0-9a-fA-F]{12}$"
                  },
                  "eventType": {
                    "description": "root.cert.added\nroot.cert.expired\nroot.cert.revoked",
                    "enum": [
                      "mo.prov.cert.updated",
                      "mo.prov.cert.deleted",
                      "mo.prov.cert.factory.reset",
                      "mo.contract.delivered.to.oem",
                      "mo.contract.created.sent.to.oem",
                      "mo.contract.updated.sent.to.oem",
                      "mo.contract.deleted.sent.to.oem",
                      "mo.contract.rejected.by.oem",
                      "mo.contract.queued.to.oem",
                      "oem.contract.created",
                      "oem.contract.updated",
                      "oem.contract.deleted"
                    ]
                  },
                  "xsdMsgDefNamespace": {
                    "description": "Which ISO Version\n",
                    "example": "urn:iso:15118:2:2013:MsgDef",
                    "enum": [
                      "urn:iso:15118:2:2013:MsgDef",
                      "urn:iso:15118:20:2022:MsgDef"
                    ]
                  },
                  "payload": {
                    "type": "object",
                    "required": [
                      "emaid",
                      "pcid"
                    ],
                    "properties": {
                      "emaid": {
                        "type": "string",
                        "pattern": "^[A-Za-z]{2}[-]?\\w{3}[-]?\\w{9}[-]?(\\w{1})?$",
                        "description": "The EMAID of the requested contract.\n"
                      },
                      "pcid": {
                        "type": "string",
                        "pattern": "^[a-zA-Z0-9]{17,18}$",
                        "example": "WMI123456712345678",
                        "description": "The related Provisioning Certificate ID."
                      },
                      "contractCert": {
                        "type": "string",
                        "description": "Contract Certificate in base64 encoded PEM form",
                        "pattern": "Contract Certificate in base64 encoded DER form"
                      },
                      "cpsSignerRootFingerprint": {
                        "type": "string",
                        "description": "The SHA256 Fingerprint of the desired V2G root CA which shall was used to sign these data with the regarding CPS signing certificate. Its optional. If not given, the CPS will decide which CPS signing V2G PKI will be renurned",
                        "example": "a76ae4c5d00e06a967554511865bfa89e79590e8a61b5a71f9ce22e039d6c370",
                        "pattern": ""
                      },
                      "cpsSignerRootCommonName": {
                        "type": "string",
                        "example": "V2G Root CA G2",
                        "description": "Common Name of used CPS V2G Root CA"
                      },
                      "signatureAlgorithm": {
                        "type": "string",
                        "enum": ["secp256r1", "secp521r1"],
                        "description": "Signature algorithm used"
                      }
                    }
                  }
                }
              },
              "examples": {
                "ISO 15118-2 Example": {
                  "value": {
                    "timestamp": "2026-02-03T00:00:00Z",
                    "eventId": "b1b86334-7c74-4ccc-b78d-d4f773d3b559",
                    "eventType": "mo.contract.created.sent.to.oem",
                    "xsdMsgDefNamespace": "urn:iso:15118:2:2013:MsgDef",
                    "payload": {
                      "emaid": "DEABCE1234567890",
                      "pcid": "WMI123456712345678",
                      "contractCert": "MIICXjCCAeS...",
                      "cpsSignerRootFingerprint": "a76ae4c5d00e06a967554511865bfa89e79590e8a61b5a71f9ce22e039d6c370",
                      "cpsSignerRootCommonName": "V2G Root CA G2",
                      "signatureAlgorithm": "secp256r1"
                    }
                  }
                },
                "ISO 15118-20 Example": {
                  "value": {
                    "timestamp": "2026-02-03T00:00:00Z",
                    "eventId": "c2c97445-8d85-5ddd-c89e-e5f884e4c660",
                    "eventType": "mo.contract.created.sent.to.oem",
                    "xsdMsgDefNamespace": "urn:iso:15118:20:2022:MsgDef",
                    "payload": {
                      "emaid": "DEABCE1234567890",
                      "pcid": "WMI123456712345678",
                      "contractCert": "MIICXjCCAeS...",
                      "cpsSignerRootFingerprint": "b87bf5d6e11f17b968665622976cga9af8a6a1f9b72c6b82gad33f14ae7d481",
                      "cpsSignerRootCommonName": "V2G Root CA G2",
                      "signatureAlgorithm": "secp521r1"
                    }
                  }
                }
              }
            }
          },
          "description": ""
        },
        "description": "This body will be used if events regarding a PCIDs and EMAIDS are fired.\n\n### MO related:\n* mo.prov.cert.deleted\n* mo.prov.cert.updated\n* mo.prov.cert.updated.factory.reset\n* mo.contract.delivered.to.oem\n* mo.contract.created.sent.to.oem\n* mo.contract.updated.sent.to.oem\n* mo.contract.deleted.sent.to.oem\n* mo.contract.rejected.by.oem\n* mo.contract.queued.to.oem\n### OEM related:\n* oem.contract.created\n* oem.contract.updated\n* oem.contract.deleted\n"
      }
    }
  },
  "components": {
    "schemas": {}
  }
}

